baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yunwoong7.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

analytics:
  provider: "google"
  google:
    tracking_id: "G-198HT4ZSJZ"
    anonymize_ip: false # default

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
