#-------------------------------
# General Site Settings

title: Be Original
logo: 
author: yunwoong Kim
description: 김윤웅의 개인 블로그입니다.
email: yunwoong7@gmail.com
phone: +82 010 4126 2003
address: 71-18, Gugal-ro, Giheung-gu, Yongin-si, Gyeonggi-do, Republic of Korea
copyright: Copyright © Yunwoong

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.# Learn more at: http://support.google.com/analytics/answer/1008065
google-analytics: "G-198HT4ZSJZ"


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Software <br> Developer

social:
#- {icon: "ti-facebook", link: "#"}
#- {icon: "ti-instagram", link: "#"}
- {icon: "ti-github", link: "https://github.com/yunwoong7"}
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/윤웅-김-17832919a/"}

#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Hello, I'm Kim Yun Woong. I am currently working at C&C, SK Corporation. I like to develop programs, fortunately, I had many good opportunities to develop them after I joined the company, so I was able to experience various things. I will try my best to keep my passion for development. Thank you.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
#work-process:
#  - title : "Research and Plan"
#    icon : "assets/images/icons/plan.png"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
#
#  - title : "Design and Develop"
#    icon : "assets/images/icons/design.png"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
#
#  - title : "Deliver"
#    icon : "assets/images/icons/print.png"
#    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
#
#
## My Team Section
#team:
#  - title : "Jack Schenziwe"
#    image : "assets/images/team/member-1.png"
#    designation : "Project Manager"
#
#  - title : "Julias Carlie"
#    image : "assets/images/team/member-2.png"
#    designation : "Web Developer"
#
#  - title : "John Doe"
#    image : "assets/images/team/member-3.png"
#    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Python, color: '#fdb157', value: '95%'}
- {name: C, color: '#9473e6', value: '90%'}
- {name: Java, color: '#bdecf6', value: '70%'}
- {name: Javascrip, color: '#ffbcaa', value: '80%'}
- {name: SQL, color: '#b5fbe2', value: '90%'}
- {name: DL/ML, color: '#ffbcc8', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: SKT UKey 2.0 Project, icon: 'icon-2.png', date: 'Jan 2011 - Dec 2011', organization: 'Junior Software Developer'}
- {name: SKT Product Development, icon: 'icon-2.png', date: 'Mar 2012 - Dec 2012', organization: 'Junior Software Developer'}
- {name: SKT Reorganization of Address System, icon: 'icon-2.png', date: 'Jan 2013 - Oct 2013', organization: 'Junior Software Developer'}
- {name: SKB Product Development, icon: 'icon-1.png', date: 'Nov 2013 - Oct 2014', organization: 'Senior Software Developer'}
- {name: SKT Swing Project, icon: 'icon-1.png', date: 'Nov 2014 - Sep 2017', organization: 'Senior Software Developer'}
- {name: OCR Solution, icon: 'icon-3.png', date: 'Oct 2018 - May 2019', organization: 'Senior Software Developer'}
- {name: Database Solution, icon: 'icon-3.png', date: 'Jul 2019 - Oct 2019', organization: 'Senior Software Developer'}
- {name: RPA Solution, icon: 'icon-3.png', date: 'Jan 2020 - Nov 2020', organization: 'Senior Software Developer'}


#-------------------------------
# Education Section

#education-title: Education
#education:
#- {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
#- {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
#- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
#- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

services-title: Interests
services:
- {
    name: Computer Vision,
    icon: ti-eye,
    description: 'I am currently most interested in creating systems that autonomously do what a human vision can do, and I am developing a variety of related programs.',
    active: # Add true to select section
  }
- {
    name: RPA,
    icon: ti-bolt,
    description: 'I want to develop software that helps real people work in a way that is much more advanced than macros, and I want to think and solve various methods.',
    active: true # Add true to select section
  }
- {
    name: Big Data,
    icon: ti-image,
    description: 'I would like to analyze the complex structured and unstructured data collected and solve many business problems that could not be solved before.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/ReST.png"
    url: "portfolio/2020-11-25-ReST"
    
  - image : "assets/images/portfolio/ocr.png"
    url: "portfolio/2019-05-31-image_ocr"
    
  - image : "assets/images/portfolio/EDS.png"
    url: "portfolio/2019-09-09-EDS"

  - image : "assets/images/portfolio/measure_social_distancing.png"
    url: "portfolio/2020-03-03-measuring_social_distance"

  - image : "assets/images/portfolio/face_mask_detector.png"
    url: "portfolio/2020-06-08-face_mask_detector"


# Portfolio Page
portfolio-label:
- {
    title : "RPA",
    type : "rpa"
  }
- {
    title : "DeepLearning",
    type : "deeplearning"
  }
- {
    title : "MachineLearning",
    type : "machineLearning"
  }
- {
    title : "OCR",
    type : "ocr"
  }
- {
    title : "DataBase",
    type : "db"
  }
- {
    title : "Face Applications",
    type : "face"
  }
- {
    title : "Object Detection",
    type : "detection"
  }
- {
    title : "Object Tracking",
    type : "tracking"
  }

portfolio-items:
  - image : "assets/images/portfolio/ReST.png"
    url: "portfolio/2020-11-25-ReST"
    portfolio-type:
     - type: "rpa"
     - type: "machineLearning"
      
  - image : "assets/images/portfolio/ocr.png"
    url: "portfolio/2019-05-31-image_ocr"
    portfolio-type:
      - type: "ocr"
      - type: "machineLearning"
      - type: "deeplearning"
      - type: "rpa"
      
  - image : "assets/images/portfolio/EDS.png"
    url: "portfolio/2019-09-09-EDS"
    portfolio-type:
      - type: "rpa"
      - type: "db"

  - image : "assets/images/portfolio/measure_social_distancing.png"
    url: "portfolio/2020-03-03-measuring_social_distance"
    portfolio-type:
      - type: "deeplearning"
      - type: "detection"
      - type: "tracking"

  - image : "assets/images/portfolio/face_mask_detector.png"
    url: "portfolio/2020-06-08-face_mask_detector"
    portfolio-type:
      - type: "deeplearning"
      - type: "face"
      - type: "detection"

  - image : "assets/images/portfolio/automatic_order/automation_order.png"
    url: "portfolio/2020-03-05-automatic_order"
    portfolio-type:
      - type: "rpa"
      
  - image : "assets/images/portfolio/drowsiness_detection.png"
    url: "portfolio/2019-06-10-drowsiness_detection"
    portfolio-type:
      - type: "deeplearning"
      - type: "face"
      - type: "detection"

  - image: "assets/images/portfolio/predicting_customers_withdrawn.png"
    url: "portfolio/2017-09-12-predicting_customers_withdrawn"
    portfolio-type:
      - type: "machineLearning"
#
#  - image : "assets/images/portfolio/item-3.png"
#    url: "#"
#    portfolio-type:
#      - type: "rpa"
#      - type: "machineLearning"
#      - type: "deeplearning"
#
#  - image : "assets/images/portfolio/item-7.png"
#    url: "#"
#    portfolio-type:
#      - type: "machineLearning"


#-------------------------------
# Testimonials Section

#testimonial-items:
#  - name: "Steve"
#    image: "assets/images/testimonial/who1.jfif"
#    designation : "CEO, Funder"
#    content : "매우 착하고 좋은사람이며 성격이 좋습니다. <strong>하지만 일은 못합니다.</strong> 나름대로 본인한 노력한다고 하는편입니다."
#
#  - name: "Choo Miae"
#    image: "assets/images/testimonial/who2.jfif"
#    designation: "CEO, Funder"
#    content: "일을 완결적으로 처리하는 노력하는 사람입니다. <strong>하지만 매우 이기적이며 타인을 배려하지 않습니다.</strong> 앞으로 어떻게 일하는지 두고 봐야합니다."
#
#  - name: "Donald John Trump"
#    image: "assets/images/testimonial/who1.jfif"
#    designation: "CEO, Funder"
#    content: "자기 주장이 강하며 추진력이 있습니다. <strong>하지만 제대로 들여다보면 제정상이 아닙니다.</strong> 그래서 나름 매력이 있습니다."


#-------------------------------
# Client Slider Section

#client-slider-items:
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
#
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: myybnenz
